project_name: OliveTin
before:
  hooks:
    - go mod tidy
    - make grpc
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

    goarch:
      - amd64
      - arm64
      - arm

    goarm:
      - 5 # For old RPIs

    main: cmd/OliveTin/main.go

    ignore:
      - goos: darwin
        goarch: arm # Mac does not work on [32bit] arm

      - goos: windows
        goarch: arm

      - goos: windows # Does anyone use Windows on arm64?
        goarch: arm64

    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }}

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Commit }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

archives:
  - 
    format: tar.gz

    files: 
      - var/config.yaml
      - LICENSE
      - README.md
      - Dockerfile
      - webui
      - OliveTin.service

    replacements:
      darwin: macOS

    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"

    wrap_in_directory: true

    format_overrides:
      - goos: windows
        format: zip
