name: "Build Snapshot"

on: [push]

jobs:
  build-snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64,arm

      - name: Setup Go
        uses: actions/setup-go@v2
        with: 
          go-version: '^1.16.0'

      - name: grpc
        run: make grpc

      - name: goreleaser
        uses: goreleaser/goreleaser-action@v2
        with: 
          distribution: goreleaser
          version: latest
          args: release --snapshot --rm-dist

      - name: Archive binaries
        uses: actions/upload-artifact@v2
        with: 
          name: dist
          path: dist/OliveTin*.*

      - name: Archive integration tests
        uses: actions/upload-artifact@v2
        with: 
          name: integration-tests
          path: integration-tests
