---
name: "Build Tag"

on:
  push:
    tags:
      - '*'

jobs:
  build-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64,arm

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: webui/package-lock.json

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18.0'
          cache: true

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_KEY }}

      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: grpc
        run: make grpc

      - name: goreleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist --parallelism 1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Archive binaries
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/OliveTin*.*

      - name: Archive integration tests
        uses: actions/upload-artifact@v2
        with:
          name: integration-tests
          path: integration-tests
