name: "Codestyle checks"

on: [push]

jobs:
  codestyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: actions/setup-go@v2

      - name: daemon
        run: make daemon-codestyle

      - name: webui
        run: make webui-codestyle
