name: "Codestyle checks"

on:
  push:
    paths:
      - 'cmd/**'
      - 'internal/**'
      - 'webui/**'
      - 'integration-tests/**'
      - 'OliveTin.proto'


jobs:
  codestyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with: 
          go-version: '^1.16.0'

      - name: deps
        run: make grpc

      - name: daemon
        run: make daemon-codestyle

      - name: webui
        run: make webui-codestyle
