name: "Jenkins RC Build"

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs: 
      reason:
        description: "Reason"
        required: true
        default: "no reason given"

jobs:
  codestyle:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger jenkins job
        uses: jabbukka/jenkins-trigger@main
        with:
          url: ${{ secrets.JENKINS_URL }}
          job_name: "OliveTin/OliveTin-rc-builder"
          user_name: ${{ secrets.JENKINS_USER }}
          api_token: ${{ secrets.JENKINS_TOKEN }}
          wait: "true"
          timeout: "1000"
