name: "RC Build"

on: [push]

jobs:
  rcbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with: 
          go-version: '^1.16.0'

      - name: grpc
        run: make grpc

      - name: goreleaser
        uses: goreleaser/goreleaser-action@v2
        with: 
          distribution: goreleaser
          version: latest
          args: release --snapshot --rm-dist

      - name: Archive binaries
        uses: actions/upload-artifact@v2
        with: 
          name: dist
          path: dist/OliveTin-**

      - name: Archive integration tests
        uses: actions/upload-artifact@v2
        with: 
          name: integration-tests
          path: integration-tests
